# 05_aldex2.R
# Rameen Jafri
#
#
# Differential abundance analysis between vegan and omnivore gut microbiomes
# Tool: ALDEx2 - handles compositional microbiome data via Monte Carlo Dirichlet sampling
# ALDEx2 is preferred over DESeq2 here because it explicitly models compositional
# uncertainty and shrinks extreme fold changes from sparse counts, reducing false
# positives at low sample sizes (n=3 per group).
#
# Run from: ~/BINF_DESKTOP/BINF6110/assignment03/
# Input: results/bracken/data_for_deseq2.rds (generated by 04_diversity.R)

library(ALDEx2)
library(ggplot2)
library(dplyr)

# ─────────────────────────────────────────────
# 1. LOAD DATA
# ─────────────────────────────────────────────

data       <- readRDS("results/bracken/data_for_deseq2.rds")
otu_counts <- data$otu_counts
metadata   <- data$metadata

# ─────────────────────────────────────────────
# 2. PREVALENCE FILTERING
# ─────────────────────────────────────────────
# Retain taxa present with >= 10 reads in at least 2 of 6 samples

min_samples <- 2
min_reads   <- 10

prevalence_keep <- rowSums(otu_counts >= min_reads) >= min_samples
otu_filtered    <- otu_counts[prevalence_keep, ]
cat("Taxa before filtering:", nrow(otu_counts), "\n")
cat("Taxa after prevalence filtering:", nrow(otu_filtered), "\n")

# ─────────────────────────────────────────────
# 3. RUN ALDEX2
# ─────────────────────────────────────────────

# Condition vector must match column order of otu_filtered
conditions <- metadata[colnames(otu_filtered), "diet_group"]
cat("Sample order:", colnames(otu_filtered), "\n")
cat("Conditions:  ", as.character(conditions), "\n")

# ALDEx2 requires integer counts
otu_int <- round(otu_filtered)

# Run ALDEx2 with Welch's t-test and Wilcoxon test
# mc.samples = 128 is standard; increase to 256-512 for publication
set.seed(42)
aldex_out <- aldex(
  reads      = otu_int,
  conditions = as.character(conditions),
  mc.samples = 128,
  test       = "t",
  effect     = TRUE,
  denom      = "all"
)

# Summary
cat("\nALDEx2 Results (first 10 rows):\n")
print(head(aldex_out[order(aldex_out$wi.eBH), ], 10))

# Filter significant results: BH-corrected Wilcoxon p < 0.05 and |effect| > 0.5
# ALDEx2 uses effect size (not log2FC) as the measure of difference
sig_aldex <- aldex_out %>%
  tibble::rownames_to_column("species") %>%
  filter(wi.eBH < 0.05, abs(effect) > 0.5) %>%
  arrange(wi.eBH)

cat("\nSignificantly differentially abundant taxa (wi.eBH < 0.05, |effect| > 0.5):\n")
print(sig_aldex %>% select(species, effect, wi.eBH))

# Save full results
write.csv(aldex_out %>% tibble::rownames_to_column("species"),
          "results/bracken/aldex2_results.csv", row.names = FALSE)
cat("Saved: results/bracken/aldex2_results.csv\n")

# ─────────────────────────────────────────────
# 4. MW PLOT (ALDEx2 equivalent of volcano plot)
# ─────────────────────────────────────────────
# MW plot: median Within-group variation (x) vs median Between-group effect (y)
# Points in the expected range of technical variation fall near y=0
# Taxa with large between-group effects appear at top/bottom

aldex_df <- aldex_out %>%
  tibble::rownames_to_column("species") %>%
  mutate(
    significance = case_when(
      wi.eBH < 0.05 & effect >  0.5 ~ "Enriched in Vegan",
      wi.eBH < 0.05 & effect < -0.5 ~ "Enriched in Omnivore",
      TRUE                           ~ "Not significant"
    )
  )

p_mw <- ggplot(aldex_df, aes(x = diff.win, y = diff.btw, color = significance)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c(
    "Enriched in Vegan"    = "#2ecc71",
    "Enriched in Omnivore" = "#e74c3c",
    "Not significant"      = "grey60"
  )) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ggrepel::geom_text_repel(
    data  = filter(aldex_df, wi.eBH < 0.05, abs(effect) > 0.5),
    aes(label = species),
    size  = 2.5, max.overlaps = 15
  ) +
  labs(title = "ALDEx2 MW Plot: Vegan vs Omnivore",
       x     = "Dispersion (median within-group variation)",
       y     = "Difference (median between-group)",
       color = "") +
  theme_bw() +
  theme(legend.position = "bottom")

ggsave("figures/aldex2_mw_plot.png", p_mw, width = 8, height = 6, dpi = 300)
cat("Saved: figures/aldex2_mw_plot.png\n")

# ─────────────────────────────────────────────
# 5. EFFECT SIZE BAR PLOT
# ─────────────────────────────────────────────

if (nrow(sig_aldex) > 0) {
  sig_aldex <- sig_aldex %>%
    mutate(direction = ifelse(effect > 0, "Enriched in Vegan", "Enriched in Omnivore"))
  
  p_effect <- ggplot(sig_aldex,
                     aes(x = reorder(species, effect), y = effect, fill = direction)) +
    geom_col() +
    coord_flip() +
    scale_fill_manual(values = c("Enriched in Vegan"    = "#2ecc71",
                                 "Enriched in Omnivore" = "#e74c3c")) +
    labs(title = "Differentially Abundant Taxa (ALDEx2)",
         x     = "Species",
         y     = "Effect Size (positive = enriched in Vegan)",
         fill  = "") +
    theme_bw() +
    theme(legend.position = "bottom")
  
  ggsave("figures/aldex2_effect_plot.png", p_effect, width = 9, height = 7, dpi = 300)
  cat("Saved: figures/aldex2_effect_plot.png\n")
} else {
  cat("No significant taxa to plot.\n")
}