# 05_deseq2.R
# Rameen Jafri
#
#
# Differential abundance analysis between vegan and omnivore gut microbiomes
# Tool: DESeq2
#
# Run from: ~/BINF_DESKTOP/BINF6110/assignment03/
# Input: results/bracken/data_for_deseq2.rds (generated by 04_diversity.R)

library(DESeq2)
library(ggplot2)
library(dplyr)


# 1. LOAD DATA   -----------------

data    <- readRDS("results/bracken/data_for_deseq2.rds")
otu_counts <- data$otu_counts
metadata   <- data$metadata

# Ensure metadata diet_group is a factor with Omnivore as reference
metadata$diet_group <- factor(metadata$diet_group,
                              levels = c("Omnivore", "Vegan"))


# 2. FILTER TO HUMAN GUT TAXA   -----------------
# Kraken2 classifies against all domains of life. We filter to genera
# represented in the Unified Human Gastrointestinal Genome (UHGG) catalogue
# (Almeida et al., 2021) to remove environmental false positives.

gut_genera <- c(
  "Bacteroides", "Phocaeicola", "Parabacteroides", "Alistipes", "Prevotella",
  "Paraprevotella", "Segatella", "Odoribacter", "Barnesiella",
  "Faecalibacterium", "Ruminococcus", "Lachnospira", "Coprococcus",
  "Agathobacter", "Roseburia", "Blautia", "Eubacterium", "Dorea",
  "Subdoligranulum", "Flavonifractor", "Oscillibacter", "Lawsonibacter",
  "Dysosmobacter", "Butyrivibrio", "Clostridium", "Erysipelatoclostridium",
  "Bifidobacterium", "Collinsella", "Slackia", "Adlercreutzia",
  "Akkermansia", "Sutterella", "Bilophila", "Dialister",
  "Escherichia", "Streptococcus", "Lactobacillus", "Enterococcus",
  "Fusobacterium", "Methanobrevibacter", "Phascolarctobacterium",
  "Wujia", "Simiaoa", "Butyricoccus", "Anaerobutyricum",
  "Intestinimonas", "Enorma", "Gordonibacter", "Senegalimassilia",
  "Eisenbergiella", "Vescimonas", "Megasphaera", "Acidaminococcus",
  "Veillonella", "Porphyromonas", "Tannerella", "Prevotellaceae"
)

gut_pattern <- paste0("^(", paste(gut_genera, collapse = "|"), ")\\b")
gut_keep    <- grepl(gut_pattern, rownames(otu_counts))
otu_gut     <- otu_counts[gut_keep, ]
cat("Taxa before gut filtering:", nrow(otu_counts), "\n")
cat("Taxa after gut filtering:", nrow(otu_gut), "\n")

# Also apply minimum abundance filter
keep         <- rowSums(otu_gut) >= 10
otu_filtered <- otu_gut[keep, ]
cat("Taxa after abundance filtering:", nrow(otu_filtered), "\n")


# 3. RUN DESEQ2   -----------------

dds <- DESeqDataSetFromMatrix(
  countData = round(otu_filtered),   # DESeq2 requires integers
  colData   = metadata,
  design    = ~ diet_group
)

dds <- DESeq(dds)

# Extract results with cooksCutoff disabled to recover outlier-flagged taxa
# (DESeq2 flags ~16% of taxa as outliers at n=3, removing potentially real signals)
res <- results(dds,
               contrast     = c("diet_group", "Vegan", "Omnivore"),
               alpha        = 0.05,
               cooksCutoff  = FALSE)

# Apply LFC shrinkage using apeglm to stabilize inflated fold changes
# from low-count taxa, which is recommended at small sample sizes
library(apeglm)
res_shrunk <- lfcShrink(dds,
                        coef = "diet_group_Vegan_vs_Omnivore",
                        type = "apeglm",
                        res  = res)

# Summarize results
cat("\nDESeq2 Results Summary (after LFC shrinkage):\n")
summary(res_shrunk)

# Filter significant results: padj < 0.05 and |log2FC| > 1
res_df <- as.data.frame(res_shrunk) %>%
  tibble::rownames_to_column("species") %>%
  filter(!is.na(padj)) %>%
  arrange(padj)

sig_taxa <- res_df %>%
  filter(padj < 0.05, abs(log2FoldChange) > 1)

cat("\nSignificantly differentially abundant taxa (padj < 0.05, |LFC| > 1):\n")
print(sig_taxa %>% select(species, log2FoldChange, padj))

# Save full results table
write.csv(res_df, "results/bracken/deseq2_results.csv", row.names = FALSE)
cat("Saved full results: results/bracken/deseq2_results.csv\n")


# 4. VOLCANO PLOT -----------------

res_df <- res_df %>%
  mutate(
    significance = case_when(
      padj < 0.05 & log2FoldChange >  1 ~ "Enriched in Vegan",
      padj < 0.05 & log2FoldChange < -1 ~ "Enriched in Omnivore",
      TRUE                               ~ "Not significant"
    )
  )

# MA-style scatter plot: mean abundance (x) vs log2FC (y)
# This mirrors the ALDEx2 MW plot aesthetic
res_df <- res_df %>%
  mutate(baseMean_log = log10(baseMean + 1))

p_ma <- ggplot(res_df, aes(x = baseMean_log, y = log2FoldChange,
                           color = significance)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_color_manual(values = c(
    "Enriched in Vegan"     = "#2ecc71",
    "Enriched in Omnivore"  = "#e74c3c",
    "Not significant"       = "grey60"
  )) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  ggrepel::geom_text_repel(
    data  = filter(res_df, padj < 0.05, abs(log2FoldChange) > 1),
    aes(label = species),
    size  = 2.5, max.overlaps = 15
  ) +
  labs(title = "Differential Abundance: Vegan vs Omnivore",
       x     = "Mean Abundance (log10)",
       y     = "log2 Fold Change (Vegan / Omnivore)",
       color = "") +
  theme_bw() +
  theme(legend.position = "bottom")

ggsave("figures/ma_plot.png", p_ma, width = 8, height = 6, dpi = 300)
cat("Saved: figures/ma_plot.png\n")


# 5. DIFFERENTIAL ABUNDANCE BAR PLOT   -----------------

if (nrow(sig_taxa) > 0) {
  sig_taxa <- sig_taxa %>%
    mutate(direction = ifelse(log2FoldChange > 0,
                              "Enriched in Vegan", "Enriched in Omnivore"))
  
  p_taxa <- ggplot(sig_taxa,
                   aes(x = reorder(species, log2FoldChange),
                       y = log2FoldChange, fill = direction)) +
    geom_col() +
    coord_flip() +
    scale_fill_manual(values = c("Enriched in Vegan"    = "#2ecc71",
                                 "Enriched in Omnivore" = "#e74c3c")) +
    labs(title = "Differentially Abundant Taxa (DESeq2)",
         x     = "Species",
         y     = "log2 Fold Change (Vegan / Omnivore)",
         fill  = "") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.text.y = element_text(size = 10),
          panel.grid.major.y = element_line(color = "grey90"))
  
  ggsave("figures/differential_abundance.png", p_taxa,
         width = 9, height = 6, dpi = 300)
  cat("Saved: figures/differential_abundance.png\n")
} else {
  cat("No significant taxa to plot.\n")
}